// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byhkitxlcaxbddssnypy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5aGtpdHhsY2F4YmRkc3NueXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDM1MzYsImV4cCI6MjA3NDM3OTUzNn0.qZ5uYrQ5Q7X_D4NzrYHcIKmcZ8Yuy_bwe8qiGfbHBV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});